[package]
name = "pegmd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.7"
pest_derive = { version = "2.7", features = [ "grammar-extras" ] }
strum = "0.25"
strum_macros = "0.25"